const express = require('express');
const cors = require('cors');
const { randomUUID } = require('node:crypto');
const mongoose = require('mongoose');
const app = express();
app.disable('x-powered-by');
const origins = (process.env.CORS_ORIGIN || 'http://localhost:8081').split(',').map(s => s.trim());
app.use((req, res, next) => { req.requestId = randomUUID(); res.set({ 'X-Request-ID': req.requestId, 'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'no-store', 'Referrer-Policy': 'no-referrer' }); next(); });
app.use(cors({ origin: origins, methods: ['GET', 'POST', 'PATCH', 'DELETE'], allowedHeaders: ['Content-Type', 'Authorization'] }));
app.use(express.json({ limit: '16kb' }));
app.get('/', (req, res) => res.json({ service: 'LibraReserve API', version: '1.0.0' }));
app.get('/api/health', async (req, res) => { if (mongoose.connection.readyState !== 1) return res.status(503).json({ status: 'unavailable' }); await mongoose.connection.db.command({ ping: 1 }); res.json({ status: 'ok' }); });
app.use('/api/auth', require('./routes/auth'));
app.use('/api/books', require('./routes/books'));
app.use('/api/reservations', require('./routes/reservations'));
app.use((req, res) => res.status(404).json({ message: 'Endpoint not found.' }));
app.use((error, req, res, next) => {
  const status = error.status === 400 || error.status === 413 ? error.status : error.name === 'ValidationError' || error.name === 'CastError' ? 400 : 500;
  if (status === 500) console.error(JSON.stringify({ requestId: req.requestId, error: error.name || 'Error' }));
  res.status(status).json({ message: status === 500 ? 'Server error. Please try again.' : status === 413 ? 'Request body is too large.' : 'Invalid request data.', requestId: req.requestId });
});
module.exports = app;
