import { useLibrary } from '@/state/library';
import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, Field, Icon, Message, Screen, u } from '@/components/library/ui';
export default function Signup() {
  const { register } = useLibrary(); const [busy, setBusy] = useState(false);
  const [name, setName] = useState(''), [student, setStudent] = useState(''), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [department, setDepartment] = useState(''), [accepted, setAccepted] = useState(false), [error, setError] = useState('');
  async function submit() { if (busy) return; if (!name.trim() || !student.trim() || !department.trim() || !email.includes('@') || password.length < 8 || !accepted) { setError('Complete all fields, use a password of at least 8 characters, and accept the borrowing terms.'); return; } setBusy(true); setError(''); try { await register({ name, studentId: student, department, email, password, acceptedTerms: accepted }); setPassword(''); router.replace('/home'); } catch (e) { setError(e instanceof Error ? e.message : 'Registration failed.'); } finally { setBusy(false); } }
  return <Screen title="New reader card" subtitle="JOIN YOUR CAMPUS LIBRARY" back="/login"><View style={{ gap: 8 }}><Text style={u.title}>A world of ideas awaits.</Text><Text style={u.body}>Create your library account using your university details.</Text></View><Card><Field label="FULL NAME" placeholder="Alex Morgan" value={name} onChangeText={setName} autoComplete="name" /><Field label="STUDENT / STAFF ID" placeholder="IT20240001" value={student} onChangeText={setStudent} /><Field label="UNIVERSITY EMAIL" placeholder="you@university.edu" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" /><Field label="DEPARTMENT / FACULTY" placeholder="School of Computing" value={department} onChangeText={setDepartment} /><Field label="PASSWORD" placeholder="At least 8 characters" value={password} onChangeText={setPassword} secureTextEntry autoComplete="new-password" /><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: accepted }} onPress={() => setAccepted(!accepted)} style={u.row}><Icon name={accepted ? 'check-square' : 'square'} /><Text style={[u.small, { flex: 1 }]}>I agree to the library borrowing terms and late-return policy.</Text></Pressable>{!!error && <Message error>{error}</Message>}<Button busy={busy} icon="arrow-right" onPress={submit}>Create account</Button></Card><Pressable onPress={() => router.replace('/login')}><Text style={[u.link, { textAlign: 'center' }]}>Already have an account? Sign in</Text></Pressable></Screen>;
}
