const { test } = require('node:test');
const assert = require('node:assert/strict');
const { MongoMemoryServer } = require('mongodb-memory-server');
const mongoose = require('mongoose');
const User = require('../models/User');
const Session = require('../models/Session');
const Book = require('../models/Book');
const { seedBooks } = require('../services/catalogue');
const { today } = require('../services/pickup');
test('real database: accounts, concurrent holds, ownership, persistence, session revocation and expiry', { timeout: 240000 }, async t => {
  const mongo = await MongoMemoryServer.create();
  t.after(async () => { await mongoose.disconnect(); await mongo.stop(); });
  await mongoose.connect(mongo.getUri(), { dbName: 'isolated_tests' });
  await Promise.all([User.init(), Session.init(), Book.init()]); await seedBooks();
  const server = require('../app').listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = 'http://127.0.0.1:' + server.address().port + '/api';
  async function request(route, method='GET', body, token) { const response = await fetch(base + route, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }); return { status: response.status, data: await response.json() }; }
  const details = { name: 'Test Reader', email: 'reader@example.edu', studentId: 'S001', department: 'Computing', password: 'correct-horse-123', acceptedTerms: true };
  assert.equal((await request('/health')).status, 200);
  assert.equal((await request('/auth/register','POST',{...details,acceptedTerms:false})).status,400);
  const first = await request('/auth/register','POST',details); assert.equal(first.status,201); assert.ok(first.data.token); assert.equal(first.data.user.passwordHash,undefined);
  const stored = await User.findOne({email: details.email}).select('+passwordHash'); assert.notEqual(stored.passwordHash,details.password); assert.ok(stored.passwordHash.startsWith('$2'));
  assert.equal((await request('/auth/register','POST',details)).status,409);
  assert.equal((await request('/auth/login','POST',{email: details.email,password:'incorrect-pass'})).status,401);
  const login = await request('/auth/login','POST',{email:'READER@EXAMPLE.EDU',password: details.password}); assert.equal(login.status,200);
  assert.equal((await request('/auth/me','GET',null,login.data.token)).data.user.name,details.name);
  const second = await request('/auth/register','POST',{...details,email:'second@example.edu',studentId:'S002'}); assert.equal(second.status,201);
  const catalogue = await request('/books'); assert.equal(catalogue.data.books.length,20); assert.equal(catalogue.data.books[0].reservations,undefined);
  assert.equal((await request('/books?q=Clean%20Architecture')).data.books.length,1);
  assert.equal((await request('/books/missing')).status,404);
  const pickup = {bookId:'2',pickupDate:today(),pickupWindow:'9-11 AM'};
  assert.equal((await request('/reservations','POST',pickup)).status,401);
  assert.equal((await request('/reservations','POST',{...pickup,pickupDate:'2000-01-01'},first.data.token)).status,400);
  const racers = await Promise.all([request('/reservations','POST',pickup,first.data.token),request('/reservations','POST',pickup,second.data.token)]);
  assert.deepEqual(racers.map(r=>r.status).sort(),[201,409]);
  const winner = racers[0].status===201 ? first : second; const loser = winner===first ? second : first; const hold = racers.find(r=>r.status===201).data.reservation;
  assert.equal((await request('/books/2')).data.book.copies,0);
  assert.equal((await request('/reservations','GET',null,loser.data.token)).data.reservations.length,0);
  assert.equal((await request('/reservations/'+hold.reservationId,'DELETE',null,loser.data.token)).status,404);
  await seedBooks(); assert.equal((await request('/books/2')).data.book.copies,0);
  assert.equal((await request('/reservations','GET',null,winner.data.token)).data.reservations[0].pickupCode,hold.pickupCode);
  const cancellations = await Promise.all([request('/reservations/'+hold.reservationId,'DELETE',null,winner.data.token),request('/reservations/'+hold.reservationId,'DELETE',null,winner.data.token)]);
  assert.deepEqual(cancellations.map(r=>r.status).sort(),[200,404]); assert.equal((await request('/books/2')).data.book.copies,1);
  assert.equal((await request('/auth/logout','POST',null,first.data.token)).status,200);
  assert.equal((await request('/auth/me','GET',null,first.data.token)).status,401);
  const {hash}=require('../services/session'); await Session.updateOne({_id:hash(login.data.token)},{$set:{expiresAt:new Date(0)}});
  assert.equal((await request('/auth/me','GET',null,login.data.token)).status,401);
  const noSql = await request('/auth/login','POST',{email:{$ne:null},password:details.password}); assert.equal(noSql.status,400);
});
