import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, Text, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { Badge, Button, Card, Icon, Message, Screen, Section, u } from '@/components/library/ui';
import BookCover from '@/components/library/BookCover';
import { palette as c } from '@/constants/design-system';
import { useLibrary } from '@/state/library';
import { booksApi } from '@/services/books-api';
import type { Book } from '@/types/book';
import { SHELF_AISLES } from '@/constants/shelf-aisles';
export default function Details() {
  const { id } = useLocalSearchParams<{ id: string }>(); const library = useLibrary(); const ref = useRef(library); useEffect(() => { ref.current = library; }, [library]);
  const [book, setBook] = useState<Book | null>(null), [error, setError] = useState(''), [loading, setLoading] = useState(true);
  const bookAisle = book ? SHELF_AISLES.find(aisle => aisle.categories.includes(book.category)) : undefined;
  const load = useCallback(async () => { setLoading(true); setError(''); try { const next = ref.current.demo ? ref.current.books.find(b => b.id === id) : (await booksApi.detail(id)).book; if (!next) throw new Error('Book not found.'); setBook(next); } catch (e) { setError(e instanceof Error ? e.message : 'Cannot load book.'); } finally { setLoading(false); } }, [id]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  return <Screen title="Book details" back="/books" tab="search" demo={library.demo}>{loading ? <ActivityIndicator /> : error ? <><Message error>{error}</Message><Button outline onPress={load}>Retry</Button></> : book && <><View style={[u.row, { alignItems: 'flex-start' }]}><BookCover book={book} large /><View style={{ flex: 1, gap: 10 }}><Badge tone={book.available ? 'success' : 'warning'}>{book.available ? book.copies + ' COPIES AVAILABLE' : 'CURRENTLY UNAVAILABLE'}</Badge><Text style={u.title}>{book.title}</Text><Text style={u.body}>{book.author}</Text><Text style={u.caption}>{book.category}</Text></View></View><Card><Section title="Synopsis & overview" /><Text style={u.body}>{book.description}</Text><View style={u.divider} /><Text style={u.small}>ISBN: {book.isbn || 'Not recorded'}</Text><Text style={u.small}>Category: {book.category}</Text></Card><Section title="Shelf guide" /><Card><View style={u.between}><Icon name="map-pin" /><Badge tone="info">{library.demo ? 'SAMPLE LAYOUT' : 'CATEGORY GUIDE'}</Badge></View><Text style={u.heading}>{library.demo ? 'Floor 2 · Main stacks' : 'Browse by category aisle'}</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{SHELF_AISLES.map(aisle => { const selected = bookAisle?.id === aisle.id; return <Pressable key={aisle.id} accessibilityRole="button" accessibilityLabel={`Browse books in aisle ${aisle.id}, ${aisle.label}`} onPress={() => router.push({ pathname: '/books', params: { aisle: aisle.id } })} style={{ flex: 1, minWidth: 120, height: 96, backgroundColor: selected ? c.primarySoft : c.background, borderWidth: 1, borderColor: selected ? c.primary : c.border, borderRadius: 8, alignItems: 'center', justifyContent: 'center', gap: 6 }}><Text style={u.caption}>{aisle.label.toUpperCase()}</Text><Text style={[u.label, { color: selected ? c.primary : c.secondary }]}>{aisle.id}</Text>{selected && <Icon name="map-pin" size={14} color={c.primary} />}</Pressable>; })}</View></Card><Card><Section title="Before you reserve" /><Text style={u.body}>Choose a pickup date within the next seven days. Your confirmation includes the pickup window and collection code.</Text><Text style={u.small}>For loan periods and late-return rules, check with your library desk.</Text></Card><Button disabled={!book.available} icon="bookmark" onPress={() => router.push({ pathname: '/books/reserve', params: { id: book.id } })}>{book.available ? 'Reserve this book' : 'Currently unavailable'}</Button></>}</Screen>;
}
