import { Text, View } from 'react-native';
import { router } from 'expo-router';
import { Badge, Button, Card, Icon, Message, Screen, Section, u } from '@/components/library/ui';
import { palette as c } from '@/constants/design-system';
import { useLibrary } from '@/state/library';
export default function Confirmation() {
  const { demo, confirmation: item } = useLibrary();
  return <Screen title="Reservation confirmation" back="/books" tab="holds" demo={demo}>{!item ? <><Message>Open My reservations to view your current holds.</Message><Button onPress={() => router.replace('/books/reservations')}>My reservations</Button></> : <><View style={{ alignItems: 'center', gap: 14, paddingVertical: 16 }}><View style={{ backgroundColor: c.successSoft, padding: 22, borderRadius: 50 }}><Icon name="check" size={38} color={c.success} /></View><Badge tone="success">{demo ? 'DEMO CONFIRMED' : 'CONFIRMED'}</Badge><Text style={[u.title, { textAlign: 'center' }]}>Your next read is reserved.</Text><Text style={[u.body, { textAlign: 'center' }]}>{demo ? 'You have completed the sample reservation flow.' : 'Keep your pickup code ready when you visit.'}</Text></View><Card><Section title="Reserved title" /><Text style={u.heading}>{item.title}</Text><Text style={u.body}>{item.author}</Text><View style={u.divider} /><Section title="Collection details" /><Text style={u.body}>Library service desk</Text><Text style={u.heading}>{item.pickupDate}</Text><Text style={u.body}>{item.pickupWindow} · Sri Lanka time</Text></Card><Card style={{ alignItems: 'center', borderStyle: 'dashed', paddingVertical: 28 }}><Icon name="hash" size={26} /><Text style={u.eyebrow}>Your pickup code</Text><Text selectable style={[u.title, { letterSpacing: 2 }]}>{item.pickupCode}</Text><Text style={[u.small, { textAlign: 'center' }]}>Bring this code and your student or staff ID.</Text></Card><Button icon="archive" onPress={() => router.replace('/books/reservations')}>View my reservations</Button><Button outline onPress={() => router.replace('/books')}>Continue exploring</Button></>}</Screen>;
}
