import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, Icon, Screen, Section, u } from '@/components/library/ui';
import { useLibrary } from '@/state/library';
export default function Filters() {
  const { demo, books, query, filters, setFilters } = useLibrary(); const [category, setCategory] = useState(filters.category), [available, setAvailable] = useState(filters.available);
  const count = books.filter(b => (!available || b.available) && (category === 'All' || b.category === category) && (b.title + ' ' + b.author + ' ' + b.isbn + ' ' + b.category).toLowerCase().includes(query.trim().toLowerCase())).length;
  return <Screen title="Refine your search" back="/books" tab="search" demo={demo} action={<Pressable onPress={() => { setCategory('All'); setAvailable(false); }}><Text style={u.link}>Reset</Text></Pressable>}><Text style={u.title}>Find just what you need.</Text><Text style={u.body}>Narrow your results by subject and current availability.</Text><Section title="Subject & category" /><View style={u.chips}>{['All', ...new Set(books.map(b => b.category))].map(item => <Pressable key={item} accessibilityRole="radio" accessibilityState={{ checked: category === item }} onPress={() => setCategory(item)} style={[u.chip, category === item && u.selected]}><Text style={u.small}>{item}</Text></Pressable>)}</View><Section title="Shelf status" /><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: available }} onPress={() => setAvailable(!available)}><Card style={available ? u.selected : undefined}><View style={u.row}><Icon name={available ? 'check-square' : 'square'} /><View style={{ flex: 1 }}><Text style={[u.heading, { fontSize: 14 }]}>Available now</Text><Text style={u.small}>Only show books with copies on shelf</Text></View></View></Card></Pressable><Card><Icon name="info" /><Text style={u.small}>Availability can change as other readers reserve books. Your copy is secured after confirmation.</Text></Card><Button icon="check" onPress={() => { setFilters({ category, available }); router.replace('/books'); }}>Apply filters · {count} matches</Button></Screen>;
}
