import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { Badge, Button, Card, Icon, Message, Screen, Section, u } from '@/components/library/ui';
import { palette as c } from '@/constants/design-system';
import { useLibrary } from '@/state/library';
import type { Reservation } from '@/types/book';
import BookCover from '@/components/library/BookCover';
export default function Holds() {
  const library = useLibrary(); const ref = useRef(library); useEffect(() => { ref.current = library; }, [library]);
  const [items, setItems] = useState<Reservation[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [confirm, setConfirm] = useState<string | null>(null), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(await ref.current.listHolds()); } catch (e) { setError(e instanceof Error ? e.message : 'Cannot load reservations.'); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  async function cancel(id: string) { setBusy(true); setError(''); try { await library.cancel(id); setItems(current => current.filter(item => item.reservationId !== id)); setConfirm(null); } catch (e) { setError(e instanceof Error ? e.message : 'Cancellation failed.'); } finally { setBusy(false); } }
    return <Screen title="My reservations" subtitle="YOUR ACCOUNT SHELF" tab="holds" demo={library.demo}><View style={{ backgroundColor: c.successSoft, borderLeftWidth: 4, borderLeftColor: c.success, padding: 24, gap: 8 }}><Text style={[u.eyebrow, { color: c.success }]}>A little reading, lined up.</Text><Text style={u.title}>{items.length} active {items.length === 1 ? 'reservation' : 'reservations'}</Text><Text style={u.body}>Your books. Your pickup details. All here.</Text></View>{loading && <ActivityIndicator />}{!!error && <><Message error>{error}</Message><Button outline onPress={load}>Retry</Button></>}<Section title="Upcoming pickups" />{items.map(item => <Card key={item.reservationId}><Badge tone="success">{library.demo ? 'DEMO HOLD' : 'RESERVED'}</Badge><View style={u.row}><BookCover book={item} /><View style={{ flex: 1, gap: 6 }}><Text style={u.heading}>{item.title}</Text><Text style={u.small}>{item.author}</Text></View></View><View style={u.divider} /><Text style={u.body}>{item.pickupDate} · {item.pickupWindow}</Text><Text selectable style={[u.heading, { color: c.success }]}>{item.pickupCode}</Text>{confirm === item.reservationId ? <><Message>Cancel this hold and release the copy for another reader?</Message><Button busy={busy} onPress={() => cancel(item.reservationId)}>Confirm cancellation</Button><Button outline disabled={busy} onPress={() => setConfirm(null)}>Keep my reservation</Button></> : <Pressable onPress={() => setConfirm(item.reservationId)}><Text style={u.link}>Cancel reservation</Text></Pressable>}</Card>)}{!loading && !error && !items.length && <Card style={{ alignItems: 'center', paddingVertical: 32 }}><Icon name="bookmark" size={36} color={c.success} /><Text style={u.heading}>Your next read is waiting.</Text><Text style={[u.body, { textAlign: 'center' }]}>You have no active holds. Explore the catalogue and reserve an available title.</Text><Button onPress={() => router.push('/books')}>Find a book</Button></Card>}</Screen>;
}
