import { useRef, useState, useEffect } from 'react';
import { Pressable, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Badge, Button, Card, Icon, Message, Screen, Section, u } from '@/components/library/ui';
import BookCover from '@/components/library/BookCover';
import { useLibrary } from '@/state/library';
import { booksApi } from '@/services/books-api';
import type { Book } from '@/types/book';
function dates() { const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Colombo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); return Array.from({ length: 8 }, (_, i) => new Date(Date.parse(today + 'T00:00:00Z') + i * 86400000).toISOString().slice(0, 10)); }
export default function Reserve() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { books, demo, reserve } = useLibrary(); const [loadedBook,setLoadedBook]=useState<Book|null>(null); const book = demo ? books.find(b => b.id === id) : loadedBook;
  const days = dates(); const [date, setDate] = useState(days[1]), [window, setWindow] = useState('9-11 AM'), [error, setError] = useState(''), [busy, setBusy] = useState(false); const pending = useRef(false);
  useEffect(()=>{if(demo)return;let active=true;booksApi.detail(id).then(data=>{if(active)setLoadedBook(data.book);}).catch(()=>{if(active)setError('Cannot load this book. Return to the catalogue and try again.');});return()=>{active=false;};},[id,demo]);
  async function submit() { if (pending.current || !book) return; pending.current = true; setBusy(true); setError(''); try { await reserve(book.id, date, window); router.replace('/books/confirmation'); } catch (e) { setError(e instanceof Error ? e.message : 'Reservation failed.'); } finally { pending.current = false; setBusy(false); } }
  return <Screen title="Reserve a book" back="/books" tab="search" demo={demo}>{!book ? <Message>{error || 'Loading your selected book…'}</Message> : <><Card><View style={u.row}><BookCover book={book} /><View style={{ flex: 1, gap: 6 }}><Badge tone="info">YOUR SELECTION</Badge><Text style={u.heading}>{book.title}</Text><Text style={u.small}>{book.author}</Text></View></View></Card><Section title="Pickup point" /><Card style={u.selected}><View style={u.row}><Icon name="check-circle" /><View style={{ flex: 1 }}><Text style={u.heading}>Library service desk</Text><Text style={u.small}>Collect during your selected pickup window</Text></View></View><Text style={u.small}>Bring your student or staff card and the pickup code from your confirmation.</Text></Card><Section title="Choose a date" /><View style={u.chips}>{days.map(day => <Pressable key={day} accessibilityRole="radio" accessibilityState={{ checked: date === day }} onPress={() => setDate(day)} style={[u.chip, date === day && u.selected]}><Text style={u.small}>{day.slice(5)}</Text></Pressable>)}</View><Section title="Pickup window" /><View style={u.chips}>{['9-11 AM', '12-2 PM', '4-6 PM'].map(item => <Pressable key={item} accessibilityRole="radio" accessibilityState={{ checked: window === item }} onPress={() => setWindow(item)} style={[u.chip, window === item && u.selected]}><Text style={u.small}>{item}</Text></Pressable>)}</View><Text style={u.caption}>All pickup dates and times use Sri Lanka time.</Text><Message>{demo ? 'This creates a demo reservation only. No physical book will be held.' : 'Your copy is secured only after the library confirms this request.'}</Message>{!!error && <Message error>{error}</Message>}<Button busy={busy} disabled={!book.available} icon="check" onPress={submit}>{demo ? 'Confirm demo reservation' : 'Confirm reservation'}</Button></>}</Screen>;
}
